### ISSUE TITLE
MC 1.20 javafml error

### ISSUE THREAD

**Issue by Devilswarchild** [Kitteh6660/VariantCraftingTables#11]
![Screenshot_6](https://github.com/Kitteh6660/VariantCraftingTables/assets/27385258/e5c334cd-75cd-452c-9fb6-05172b45abb6)

the base mc 1.20 version of your forge mod is set to the wrong fml for 1.20. 

fml for 1.20: the latest is 46.0.14
fml for 1.20.1: latest is 47.0.3

[crash-2023-06-17_14.20.21-fml.txt](https://github.com/Kitteh6660/VariantCraftingTables/files/11779823/crash-2023-06-17_14.20.21-fml.txt)

**Comment by Kitteh6660** [comment]
I've removed the 1.20 tag so the mod is now labeled as requiring 1.20.1.
