### ISSUE TITLE
Compatibility w/ Visual Workbench mod?

### ISSUE THREAD

**Issue by GamerGaven** [Kitteh6660/VariantCraftingTables#3]
A while back I tried manually adding your crafting tables to the [https://www.curseforge.com/minecraft/mc-mods/visual-workbench#c38](url) mod and was unsuccessful in doing so. From what I understand, after asking the creator of that mod what I was doing wrong, was that since your mod uses a custom way to open the crafting grid it overrides the other mods functionality. So I've come here wondering if it's possible for compatibility with this mod, if that's not something you'd be interested in doing it's totally cool. :)

**Comment by Kitteh6660** [comment]
It might be possible! However, the vanilla crafting table explicitly checks if the player is within range of vanilla crafting table as opposed to tags.

I will possibly look into it however!

**Comment by Fuzss** [comment]
Fixed on my end in Visual Workbench, feel free to close this.

**Comment by Kitteh6660** [comment]
Glad to hear that!
