### ISSUE TITLE
Quark Compat Bugs

### ISSUE THREAD

**Issue by FrogBirdd** [Kitteh6660/VariantCraftingTables#4]
The tables for azalea and blossom wood from quark do not show up in JEI or the creative inventory, but the recipes exist and can be viewed via JEI.

The tables also show the wrong textures when placed, the items are correct but the blocks themselves use the models from the Better Azalea tables. Looking through the blockstates and models I was unable to find a cause for this, so maybe the issue is internal?

Might be worth noting that I do not have Better Azelea installed
![2022-03-13_20 09 33](https://user-images.githubusercontent.com/47127120/158085529-b7ebefe2-ee0c-4587-8684-9c8ca5216914.png)
.

**Comment by Kitteh6660** [comment]
Should be fixed in mod version 1.5.1.
