### ISSUE TITLE
Ecologics Compat

### ISSUE THREAD

**Issue by Freshah** [Kitteh6660/VariantCraftingTables#5]
Hello!  Just incase it's not on your radar, I figured I should report that Ecologics has merged Better Azalea's two woods, and added a new one; Walnut.  Love the mod,

**Comment by Kitteh6660** [comment]
Got it, thank you! I will take that in mind. I will get around to updating the mod to improve support for Ecologics!

**Comment by Freshah** [comment]
this can be closed, newest update sorted things out.
