### ISSUE TITLE
Axes do not break wooden blocks quickly with this mod installed

### ISSUE THREAD

**Issue by raimcm3** [Kitteh6660/VariantCraftingTables#6]
Version of the mod used: 1.7.1 for 1.19.2
Forge 43.2.3

I noticed that axes were breaking wooden blocks at the same speed as bare hands, and after removing the mod it went back to its actual speed.

While I do not know why this happens (I am very new to minecraft modding and development-related things), I noticed that when the mod is installed and a wood block is viewed through Roughly Enough Items, it does not have the "#minecraft:mineable/axe" tag.
Uninstalling the mod restored it.

**Comment by Kitteh6660** [comment]
I will look into it, thanks!

**Comment by Kitteh6660** [comment]
Should be fixed in version 1.7.2 for 1.19.2 now.
