### ISSUE TITLE
Regions Unexplored Compatibility

### ISSUE THREAD

**Issue by Numerosityy** [Kitteh6660/VariantCraftingTables#8]
Crafting tables for the Regions Unexplored wood variants would be nice ^^

**Comment by Kitteh6660** [comment]
It could be a possibility! I will look into it.

**Comment by Numerosityy** [comment]
Awesome! I would be glad to make textures for you if it makes it easier for you

**Comment by Kitteh6660** [comment]
That would be awesome!

**Comment by Kitteh6660** [comment]
I actually got around to making the crafting table textures. I worked on support for not one but six mods that will be for the upcoming update! Everything is coded and almost ready, just got to add Woodworks compat to turn logs into crafting tables.

**Comment by Kitteh6660** [comment]
It's now added in mod version 1.8.0 for Minecraft 1.19.2
