### ISSUE TITLE
Acacia Crafting Tables Transform into Archwood Crafting Tables and Vice Versa

### ISSUE THREAD

**Issue by TheQuantumTantrum** [Kitteh6660/VariantCraftingTables#9]
Breaking Acacia Crafting Tables drops an Archwood Crafting Table, despite not having Ars Nouveau installed. Breaking the archwood drops the acacia.

MC: 1.19.2
Forge : 43.2.8
Mod Version: 1.8.0

**Comment by Kitteh6660** [comment]
Should be fixed in mod version 1.8.0_1, the JAR file is uploaded to CurseForge. Once it's approved, the fix will be there :)
